version: "3"
services:
  redis:
    image: redis:latest
    container_name: cache
    expose:
      - 6379
      
  app:
    build: .
    links:
      - redis
    command: npm start
    ports:
      - 3008:3000
    environment:
      - REDIS_URL=redis://cache
    volumes:
      - .:/usr/app
