# This is a basic workflow to help you get started with Actions

name: lint
on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npm ci
      - name: Lint
        run: npm run lint:fix
      - name: Commiting lint fixes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "refactor: fixing lint"
      - name: Push changes
        run: git push